source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-minimal"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "webrick", "~> 1.8"

# Add jekyll-feed and jekyll-seo-tag (which you also seem to use based on default.html)
# Ensure they are within the default group or a relevant group
gem "jekyll-feed", "~> 0.17.0"
gem "jekyll-seo-tag", "~> 2.8.0"

# Specify the group if necessary, e.g.:
# group :jekyll_plugins do
#   gem "jekyll-feed"
#   gem "jekyll-seo-tag"
# end 